query property_types {
  featured_projects {
    project {
      builder_name
      address
      project_name
      project_type
      latitude
      langitude
      id
    }
    id
  }
  featured_properties {
    id
    purpose_type
    property {
      latitude
      longitude
      marketing_title
      marketing_description
      id
      property_id
      bath_room
      bed_room
    }
  }
  testimonials {
    id
    description
    name
    created_at
  }
}
