var markers = [
{
    "id":1,
    "type_point":"Villa",
    "location_latitude":12.965633,
    "location_longitude":77.621236,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Open Bus",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":2,
    "type_point":"Builder Floor",
    "location_latitude":12.954183,
    "location_longitude":77.654808,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Senna River prjct",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":3,
    "type_point":"Apartments",
    "location_latitude":12.963893,
    "location_longitude":77.642348,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Property 1",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":4,
    "type_point":"Individual Building",
    "location_latitude":12.960642,
    "location_longitude":77.652245,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Pompidou",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":4,
    "type_point":"Builder Floor",
    "location_latitude":12.958370,
    "location_longitude":2.294481,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Project Name 5",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":5,
    "type_point":"Builder Floor",
    "location_latitude":12.937273,
    "location_longitude":77.635387,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Property 4",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":6,
    "type_point":"Individual Building",
    "location_latitude":12.960819,
    "location_longitude":77.654507,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Beaubourg",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":7,
    "type_point":"Builder Floor",
    "location_latitude":12.953798,
    "location_longitude":77.633328,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Property 3 des Prés",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":8,
    "type_point":"Builder Floor",
    "location_latitude":12.962880,
    "location_longitude":2.287205,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Trocadero",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":9,
    "type_point":"Builder Floor",
    "location_latitude":12.965784,
    "location_longitude":77.607314,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Champs-Élysées",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
  {
    "id":10,
    "type_point":"Villa",
    "location_latitude":12.952729,
    "location_longitude":77.650564,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Notre Dame",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  },
   {
    "id":11,
    "type_point":"Villa",
    "location_latitude":12.970587,
    "location_longitude":77.618943,
    "map_image_url":"img/thumb_map_single_prjct.jpg",
    "rate":"Superb | 7.5",
    "name_point":"Property 2",
    "get_directions_start_address":"",
    "phone":"+3934245255",
    "url_point":"project-detail.html"
  }
];
