query property($limit: Int = 5, $offset: Int = 0, $order_by: [property_order_by!] = {created_on: desc}, $where: property_bool_exp ) {
  property_aggregate(where: $where){
    aggregate {
      count
    }
  }
  property(
    limit: $limit, offset: $offset, order_by: $order_by, where: $where
    ) {
    address1
    address2
    administration_fee
    amenities
    annual_increase
    application_fee
    available_on
    bank_account_id
    base_late_fee
    basis_for_owner_packets
    bath_room
    bed_room
    block
    city
    commission_type
    country_id
    created_by
    created_on
    daily_late_fee
    description
    escrow_cash
    file_id
    fiscal_year_end
    franchise_id
    grace_period
    home_warranty_expiration
    house
    id
    image_id
    insurance_expiration
    last_edited_by
    last_edited_on
    last_inspection_on
    late_fee_type
    locality
    maintenance_limit
    management_fee_percent
    market_rent
    marketing_description
    marketing_title
    minimum_management_fee
    non_rentable_unit
    note_id
    operation_status
    payment_type
    pin_code
    portfolio_name
    property_id
    property_type
    removed_from_vacancy
    rent_due_day
    rent_ready
    reserve_funds
    security_deposit
    site_manager_first_name
    site_manager_last_name
    site_manager_phone_number
    site_manager_salutation
    square_footage
    state_id
    status
    tags
    tax_authority
    use_market_rent_on_ads
    vendor_1099_tax_payer
    year_built
    youtube_url
    latitude
    longitude
  }
}
